### ISSUE TITLE
Add Basic Footer Structure

### ISSUE THREAD

**Issue by sufiankhan-dev** [sufiankhan-dev/DevUnity#1]
Create a basic structure for the footer section of the website. The footer should include placeholders for links, contact information, social media icons, and any necessary copyright information.

Requirements:

1. Add placeholder links for "About Us," "Contact," "Privacy Policy," and "Terms of Service."
2. Include space for social media icons (GitHub, Twitter, LinkedIn, etc.).
3. Add basic copyright text (e.g., "© 2024 DevUnity. All rights reserved.").

**Comment by Asad-noob69** [comment]
# Add Footer Component

Hey team! I've been working on a footer to match our nav bar - keeping it clean and consistent with our current look.

## What's in it:
- Clean, dark transparent background (like our nav)
- 4 sections that stack nicely on mobile:
 - About DevUnity
 - Quick links
 - Legal stuff
 - Social links
- Copyright bar at bottom

## Tech side:
- Built with TypeScript & Next.js
- Uses our existing color scheme
- Same Lucide icons we're using up top
- Hooks into our routing system
- Tailwind classes matching our patterns

The footer uses the same transparent dark style and hover effects as the nav, with that nice lime green accent we have (#9CE630). Everything's responsive and matches our current mobile breakpoints.

Let me know if you want me to tweak anything or if something doesn't align with what you had in mind!

Tests and screenshots coming in the comments.
![Screenshot (8)](https://github.com/user-attachments/assets/cb555596-ba5f-43f5-bfb5-4bd65e88a0d2)
![Screenshot (9)](https://github.com/user-attachments/assets/0beb48c2-5bcb-451b-8a52-c0700413deee)

**Comment by sufiankhan-dev** [comment]
It looks superb Asad! Great work👍

**Comment by kittyy6969** [comment]
Hello, I would like to help :)!

**Comment by sufiankhan-dev** [comment]
@kittyy6969 Yeah sure you can help in any other feature
